import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useReducedMotion } from '../hooks/useReducedMotion'
import PrimaryButton from './PrimaryButton'

function CreateWorkOrderModal({ isOpen, onClose, onSubmit }) {
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    // rack: '',  // Commented out - not needed for now
    // pod: '',  // Commented out - not needed for now
    // aisle: '',  // Commented out - not needed for now
    // aisleType: 'cold',  // Commented out - not needed for now
    // severity: 'medium',  // Commented out - not needed for now
    // team: 'compute',  // Commented out - not needed for now
    // model: '',  // Commented out - not needed for now
    // part_id: '',  // Commented out - not needed for now
  })
  const [loading, setLoading] = useState(false)
  const [autoGenerating, setAutoGenerating] = useState(false)
  const prefersReducedMotion = useReducedMotion()

  // Auto-generate details from title and description
  const autoGenerateDetails = (title, description) => {
    if (!title && !description) return null

    const text = `${title} ${description}`.toLowerCase()
    
    // Extract rack number (e.g., "rack a12", "rack-a12", "a12")
    const rackMatch = text.match(/(?:rack[- ]?)?([a-z])(\d+)/i)
    const rack = rackMatch ? `Rack-${rackMatch[1].toUpperCase()}${rackMatch[2]}` : ''

    // Extract pod number
    const podMatch = text.match(/pod[- ]?(\d+)/i)
    const pod = podMatch ? `Pod-${podMatch[1]}` : 'Pod-1'

    // Extract aisle
    const aisleMatch = text.match(/aisle[- ]?([a-z])/i)
    const aisle = aisleMatch ? `Aisle-${aisleMatch[1].toUpperCase()}` : 'Aisle-A'

    // Determine aisle type from keywords
    const aisleType = text.includes('hot') || text.includes('warm') ? 'hot' : 'cold'

    // Determine severity from keywords
    let severity = 'medium'
    if (text.includes('critical') || text.includes('urgent') || text.includes('emergency')) {
      severity = 'critical'
    } else if (text.includes('high') || text.includes('important')) {
      severity = 'high'
    } else if (text.includes('low') || text.includes('minor')) {
      severity = 'low'
    }

    // Determine team from keywords
    let team = 'compute'
    if (text.includes('network') || text.includes('switch') || text.includes('router')) {
      team = 'network'
    } else if (text.includes('storage') || text.includes('disk') || text.includes('drive')) {
      team = 'storage'
    }

    // Extract hardware model
    const modelMatch = text.match(/(nvidia|intel|amd|gpu|cpu|a100|h100|v100)/i)
    const model = modelMatch ? modelMatch[0].toUpperCase() : ''

    // Extract part ID
    const partMatch = text.match(/(?:part[- ]?id|part[- ]?#?)([a-z0-9-]+)/i)
    const part_id = partMatch ? partMatch[1] : ''

    return { rack, pod, aisle, aisleType, severity, team, model, part_id }
  }

  const handleTitleChange = (e) => {
    const value = e.target.value
    setFormData(prev => ({
      ...prev,
      title: value,
    }))
    
    // Auto-generate when title changes
    if (value.length > 10) {
      setAutoGenerating(true)
      setTimeout(() => {
        const autoDetails = autoGenerateDetails(value, formData.description)
        if (autoDetails) {
          setFormData(prev => ({
            ...prev,
            ...autoDetails,
          }))
        }
        setAutoGenerating(false)
      }, 500)
    }
  }

  const handleDescriptionChange = (e) => {
    const value = e.target.value
    setFormData(prev => ({
      ...prev,
      description: value,
    }))
    
    // Auto-generate when description changes (if title exists)
    if (formData.title.length > 10 && value.length > 20) {
      setAutoGenerating(true)
      setTimeout(() => {
        const autoDetails = autoGenerateDetails(formData.title, value)
        if (autoDetails) {
          setFormData(prev => ({
            ...prev,
            ...autoDetails,
          }))
        }
        setAutoGenerating(false)
      }, 500)
    }
  }

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value,
    }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    try {
      await onSubmit(formData)
      // Reset form
      setFormData({
        title: '',
        description: '',
        // rack: '',  // Commented out
        // pod: '',  // Commented out
        // aisle: '',  // Commented out
        // aisleType: 'cold',  // Commented out
        // severity: 'medium',  // Commented out
        // team: 'compute',  // Commented out
        // model: '',  // Commented out
        // part_id: '',  // Commented out
      })
      onClose()
    } catch (err) {
      console.error('Error creating work order:', err)
    } finally {
      setLoading(false)
    }
  }

  if (!isOpen) return null

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        />

        {/* Modal */}
        <motion.div
          initial={prefersReducedMotion ? { opacity: 0 } : { opacity: 0, scale: 0.95, y: 20 }}
          animate={prefersReducedMotion ? { opacity: 1 } : { opacity: 1, scale: 1, y: 0 }}
          exit={prefersReducedMotion ? { opacity: 0 } : { opacity: 0, scale: 0.95, y: 20 }}
          transition={{ duration: 0.2 }}
          className="relative w-full max-w-2xl bg-bg-elevated rounded-lg border border-border shadow-lg max-h-[90vh] overflow-hidden flex flex-col"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="px-6 py-4 border-b border-border bg-bg-elevated">
            <div className="flex items-center justify-between">
              <h2 className="text-h1 text-text-primary">Create Work Order</h2>
              <button
                onClick={onClose}
                className="p-2 text-text-tertiary hover:text-text-primary hover:bg-bg-tertiary rounded-lg transition-colors"
                aria-label="Close"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6 space-y-6">
            {/* Title */}
            <div>
              <label className="block text-sm font-medium text-text-primary mb-2">
                Title <span className="text-danger-500">*</span>
                {autoGenerating && (
                  <span className="ml-2 text-xs text-accent-500">Auto-generating details...</span>
                )}
              </label>
              <input
                type="text"
                name="title"
                value={formData.title}
                onChange={handleTitleChange}
                required
                className="w-full px-4 py-2.5 bg-bg-secondary border border-border rounded-lg text-body text-text-primary placeholder-text-tertiary focus:outline-none focus:ring-2 focus:ring-accent-500 focus:border-transparent transition-all"
                placeholder="e.g., Replace GPU Node A12"
              />
              <p className="text-xs text-text-tertiary mt-1">
                The AI will automatically generate steps and determine priority, category, and expertise level
              </p>
            </div>

            {/* Description */}
            <div>
              <label className="block text-sm font-medium text-text-primary mb-2">
                Description <span className="text-text-tertiary">(Optional)</span>
              </label>
              <textarea
                name="description"
                value={formData.description}
                onChange={handleDescriptionChange}
                rows={3}
                className="w-full px-4 py-2.5 bg-bg-secondary border border-border rounded-lg text-body text-text-primary placeholder-text-tertiary focus:outline-none focus:ring-2 focus:ring-accent-500 focus:border-transparent transition-all resize-none"
                placeholder="Additional details about the work order..."
              />
            </div>

            {/* Commented out fields - not needed for now */}
            {/* Location Section - Commented out */}
            {/* Hardware Section - Commented out */}
            {/* Priority & Team - Commented out */}

            {/* Actions */}
            <div className="flex items-center justify-end space-x-3 pt-4 border-t border-border">
              <PrimaryButton
                type="button"
                onClick={onClose}
                variant="ghost"
                disabled={loading}
              >
                Cancel
              </PrimaryButton>
              <PrimaryButton
                type="submit"
                variant="primary"
                disabled={loading}
              >
                {loading ? 'Creating...' : 'Create Work Order'}
              </PrimaryButton>
            </div>
          </form>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}

export default CreateWorkOrderModal

